@startuml
actor "Адміністратор" as Admin

usecase "Внесення до бази даних нових користувачів сервісу" as SU1
usecase "підтримання зворотнього зв‘язку з користувачами в разі виникнення запитань" as SU2
usecase "Внесення тестів, створених лінгвістами, до бази даних" as SU3
usecase "Надання результатів користувачеві" as SU4


Admin-d-> SU1
Admin-d-> SU2
Admin-d-> SU3
Admin-d-> SU4
@enduml
