@startuml
left header

        <font color=000 size=18><b>ID:</b> UC1
        <font color=000 size=18><b>Назва:</b> Реєстрація
        <font color=000 size=18><b>Учасники:</b> Гість, система
        <font color=000 size=18><b>Передумови:</b> Незареєстрований користувач
        <font color=000 size=18><b>Результат:</b> Створений обліковий запис
        <font color=000 size=18><b>Виключні ситуації:</b>
        <font color=000 size=18> EX1 Обліковий запис зареєстрований на введну пошту вже існує
        <font color=000 size=18> EX2 Повторно введений пароль не збігаєтьсях

        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Користувач|
        start
        
        : Натискає на кнопку реєстрації;
        
    |Система|
        
        : Видає форму для реєстрації;

    |Користувач|
    
        : Заповнює форму (надає свою електронну адресу, створює пароль);
        : Відправляє заповнену форму;
        
    |Система|
    
        : Обробляє дані в формі;
         note right #ffaaaa
        <b> Можлива
        <b> EX1
        end note
        
        : Створює аккаунт з унікальним ключем в базі даних;
        note right #ffaaaa
        <b> Можлива
        <b> EX2
        end note
        
    
    |Користувач|
        
        : Натискає на кнопку для активації;

    |Система|
        
        : Переводить на єкран підтвердження активації аккаунта;
       
    
    |Користувач|
        
        : Отримує повідомлення про успішне створення проєкту;
        
        stop;
    
right footer
TryEng
НТУУ КПІ ім. І.Сікорського
Київ - 2021
end footer
@enduml
