@startuml
left header

        <font color=000 size=18><b>ID:</b> UC3
        <font color=000 size=18><b>Назва:</b> Відправка завдань
        <font color=000 size=18><b>Учасники:</b> Лінгвіст, Користувач
        <font color=000 size=18><b>Передумови:</b> Користувач обрав завдання
        <font color=000 size=18><b>Результат:</b> Завдання передається користувачеві
        <font color=000 size=18><b>Виключні ситуації:</b>
        <font color=000 size=18> EХ.5 Користувач не отримав задання

        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Користувач|
        start
        
        : Натискає отримати завдання;
        
    |Лінгвіст|
        
        : Генерує завдання;
        : Завдання надсилаються користувачеві;
    |Користувач|
    
        : Отримує завдання;
         note right #ffaaaa
        <b> Можлива
        <b> EX.5
        end note
        
 
        
        stop;
    
right footer
TryEng
НТУУ КПІ ім. І.Сікорського
Київ - 2021
end footer
@enduml
