@startuml
left header

        <font color=000 size=18><b>ID:</b> UC4
        <font color=000 size=18><b>Назва:</b> Проходження завдань користувачем
        <font color=000 size=18><b>Учасники:</b> Користувач, система
        <font color=000 size=18><b>Передумови:</b> Користувач отримав завдання
        <font color=000 size=18><b>Результат:</b> Збір інформації
        <font color=000 size=18><b>Виключні ситуації:</b>
        <font color=000 size=18> EX.6 Користувач не відповів на завдання
        <font color=000 size=18> EX.7 Користувач не надіслав результат роботи


        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Користувач|
        start
        
        : Натискає пройти тест;
        
    |Система|
        
        : Відправляє завдання;
    |Користувач|
    
        : Обирає правильну відповідь;
        : Натискає кнопку підтвердження;
         note right #ffaaaa
        <b> Можлива
        <b> EX.6
        end note
        : Відправляє завершити тест;
    |Система|
        
        : Отримує результат роботи;
        note right #ffaaaa
        <b> Можлива
        <b> EX.7
        end note

        
 
        
        stop;
    
right footer
TryEng
НТУУ КПІ ім. І.Сікорського
Київ - 2021
end footer
@enduml
