@startuml
left header


        <font color=000 size=18><b>ID:</b> UC5
        <font color=000 size=18><b>Назва:</b> Перевірка завдань
        <font color=000 size=18><b>Учасники:</b> Адміністратор, система
        <font color=000 size=18><b>Передумови:</b> Наявність виконаної роботи
        <font color=000 size=18><b>Результат:</b> Інформація перевіряється на помилки
        <font color=000 size=18><b>Виключні ситуації: відсутні</b>
        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Адміністратор|
        start
        
        : Отримує завершену роботу;
        : Відправляє системі на перевірку;
        
    |Система|
        
        : Перевіряє роботу і вказує на помилки(якщо вони присутні;
        : Надсилає результат адміністратору;

    |Адміністратор|
    
        : Повідомляє користувача про результат виконаної роботи;
        
 
  
        stop;
    
right footer
TryEng
НТУУ КПІ ім. І.Сікорського
Київ - 2021
end footer
@enduml
