@startuml
left header

        <font color=000 size=18><b>ID:</b> UC6
        <font color=000 size=18><b>Назва:</b> Користувач отримує результат
        <font color=000 size=18><b>Учасники:</b> Адміністратор, Користувач
        <font color=000 size=18><b>Передумови:</b> Наявність результату
        <font color=000 size=18><b>Результат:</b> Користувач отримує результат роботи із вказаними помилками(якщо вони присутні)
        <font color=000 size=18><b>Виключні ситуації:</b> EX.8 Користувач хоче звернутись до адміністратора із питанням по тесту
        <font color=000 size=18><b>Виключні ситуації:</b> EX.9 Користувач не отримав результат
        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Адміністратор|
        start
        : Відправляє результат;
        
    |Користувач|
        
        : Отримує результат;
         note right #ffaaaa
        <b> Можлива
        <b> EX.8
        end note

        : Аналізує результат;
         note right #ffaaaa
        <b> Можлива
        <b> EX.9
        end note
        : Завершує роботу;

        stop;
    
right footer
TryEng
НТУУ КПІ ім. І.Сікорського
Київ - 2021
end footer
@enduml
